# Application config file

[app]
title = "journal-app"
description = "A backend part of sirius-journal"
jwt_secret = "SECRET"

[http_server]
host = "0.0.0.0"
port = 8000
log_level = "info"


[db]
user = "postgres"
password = "postgres"
name = "postgres"
host = "localhost"
port = 5432

[smtp]
host = "smtp.server.com"
email = "email@mail.com"
password = "some passcode"

[redis]
host = "localhost"
port = 6379
