# Application config file

[app]
title = "journal-app"
description = "A backend part of sirius-journal"
jwt_secret = "SECRET"

[http_server]
host = "0.0.0.0"
port = 8000
log_level = "info"


[db]
user = "postgres"
password = "postgres"
name = "postgres"
host = "localhost"
port = 5432
