"""move admission year attr to group relation

Revision ID: 773fd8797246
Revises: 395d6201c542
Create Date: 2024-05-15 18:28:51.028079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773fd8797246'
down_revision: Union[str, None] = '395d6201c542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('admission_year', sa.Integer(), nullable=False))
    op.drop_column('students', 'admission_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('admission_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('groups', 'admission_year')
    # ### end Alembic commands ###
