"""add unique constraints

Revision ID: 7ebe4bee0222
Revises: 773fd8797246
Create Date: 2024-06-12 00:13:02.309842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebe4bee0222'
down_revision: Union[str, None] = '773fd8797246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'classrooms', ['name'])
    op.create_unique_constraint(None, 'groups', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_constraint(None, 'classrooms', type_='unique')
    # ### end Alembic commands ###
